services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: farmer-backend-test
    restart: always
    ports:
        - "9000:9000"
    networks:
        -  database_default
networks:
  database_default:
        external: true
