version: '2'
services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: farmer-backend
    ports:
        - "9000:9000"
    networks:
        - village-network
networks:
  village-network:
        external: true
